services:
  mysql:
    image: mysql:8
    container_name: mysql8
    restart: "no"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: itsnick
      MYSQL_USER: nick
      MYSQL_PASSWORD: Nick@2025
      MYSQL_ROOT_PASSWORD: 12312345
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf  # Mount the custom my.cnf file
    networks:
      custom_network:
        ipv4_address: 192.168.100.8  # Static IP for MySql server

networks:
  custom_network:
    external: true